---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZG13YjUzb2Qy
  CLOUDINARY_KEY: MTc0NTU3MTE2MzcyMjU1
  CLOUDINARY_SECRET: YXVHc1RsRXlEaEpmVHNDQU1JQjB6YWsxbWFF
  MAPBOX_TOKEN: c2suZXlKMUlqb2liV0Z1YjJvek1EQXpJaXdpWVNJNkltTnRNR3BoYUdKNllqQTBkMmd5YTNCcWFUUmlZak00ZDJFaWZRLm9vWXBiUC1FOC04UlQ4QmlYVVNja0E=
  DB_URL: bW9uZ29kYitzcnY6Ly92YXJtYXBvdHRodXJpNDpWYXJtYV8zMDAzQGNsdXN0ZXIwLmVheWpjLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMA==
  SECRET: ZGV2b3Bzc2hhY2s=
  DB_PORT: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: manoj3003/pipelie-cicd:18
          volumeMounts:
            - name: db-connection
              mountPath: /opt
          ports:
            - containerPort: 3000
      volumes:
        - name: db-connection
          Secret:
            name: yelp-camp-secrets
      
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
